name: Build Dropserver

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_common:
    uses: teleclimber/DropServer/.github/workflows/build_common.yml@master

  test:
    needs: build_common
#    strategy:
#      fail-fast: false
#      matrix:
#        os: ['ubuntu-latest', 'macos-latest']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Download frontend-ds-host
      uses: actions/download-artifact@v2
      with:
        name: frontend-ds-host
        path: frontend-ds-host/dist/

    - name: Download frontend-ds-dev
      uses: actions/download-artifact@v2
      with:
        name: frontend-ds-dev
        path: frontend-ds-dev/dist/

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Go Tests
      run: go test -timeout=60s -race ./...

    - name: Build ds-host
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-host ./cmd/ds-host

    - name: Build ds-dev
      run: go build -ldflags="-X main.cmd_version=`git describe --tags --dirty`" -o dist/bin/ds-dev ./cmd/ds-dev

    - name: Upload ds-host
      uses: actions/upload-artifact@v2
      with:
        name: ds-host
        path: dist/bin/ds-host

    - name: Upload ds-dev
      uses: actions/upload-artifact@v2
      with:
        name: ds-dev
        path: dist/bin/ds-dev